splash = false
preload = $HOME/Pictures/wallpapers/playitaTfn.jpg
wallpaper=eDP-1,$HOME/Pictures/wallpapers/playitaTfn.jpg
wallpaper=DP-1,$HOME/Pictures/wallpapers/playitaTfn.jpg
wallpaper=DP-2,$HOME/Pictures/wallpapers/playitaTfn.jpg
wallpaper=DP-4,$HOME/Pictures/wallpapers/playitaTfn.jpg
wallpaper=DP-5,$HOME/Pictures/wallpapers/playitaTfn.jpg
wallpaper=HDMI-A-1,$HOME/Pictures/wallpapers/playitaTfn.jpg
