splash = false
preload = $HOME/Pictures/wallpapers/exiles.jpg
wallpaper=eDP-1,$HOME/Pictures/wallpapers/exiles.jpg
wallpaper=DP-1,$HOME/Pictures/wallpapers/exiles.jpg
wallpaper=DP-2,$HOME/Pictures/wallpapers/exiles.jpg
wallpaper=HDMI-A-1,$HOME/Pictures/wallpapers/exiles.jpg
