splash = false
preload = $HOME/Pictures/wallpapers/pipBoy.png

wallpaper=eDP-1,/home/javips/Pictures/wallpapers/pipBoy.png
wallpaper=DP-1,/home/javips/Pictures/wallpapers/pipBoy.png
wallpaper=DP-2,/home/javips/Pictures/wallpapers/pipBoy.png
wallpaper=HDMI-A-1,/home/javips/Pictures/wallpapers/pipBoy.png
